### ISSUE TITLE
stale version during stabilize-packages.py (hardcoded?)

### ISSUE THREAD

**Issue by kuzetsa** [GKernelCI/GBuildbot#73] opened 2018-10-11 11:27 UTC
This has been an undocumented / ongoing issue since 2017

> "Why is this still trying to download genpatches-4.9-53"

---

### "picture is worth a thousand words" ###

![404notfound](https://i.imgur.com/3ZKPvnY.png)

**Comment by mjeveritt** [comment] 2018-10-11 11:35
Really?! What build is this?!

**Comment by kuzetsa** [comment] 2018-10-11 11:42
> Really?! What build is this?!

[other_sources/1101](http://kernel1.amd64.dev.gentoo.org:8010/#/builders/16/builds/1101)

**Comment by mjeveritt** [comment] 2018-10-11 11:54
Mmm, something is very strange there .. need to explore the python script, and what commands its generating to perform those merges, but looks like something is getting cached wrong (at best...) ...

**Comment by aliceinwire** [comment] 2018-10-12 06:15
I don't think there is any hardcoded part, maybe the manifest file is broken?

**Comment by kuzetsa** [comment] 2018-10-13 03:12
the version / string isn't present in the sys-kernel/ck-sources manifest,
so if it's somewhere else I'd only be speculating (*which: "manifest file" ?*)

**Comment by mjeveritt** [comment] 2018-10-31 19:00
I have significantly re-worked the stabilize_packages script, to use pythonic file writing rather than shell. It is functional on vmz-ci-test, as you can see.
Please review https://github.com/gentoo/Gentoo_kernelCI/compare/master...mjeveritt:overhaul-stabilize?expand=1 and I will tidy up commits and rebase, and file a Pull-Request after review.

**Comment by kuzetsa** [comment] 2018-11-01 06:43
I've looked at the commits and I have no idea what the new python version does (*it's been ported to fully native python code, I think? previously was using inline code which called shell commands*)... dot dot dot

if it works better and passes sanity checks and is stable, etc. I'm not going to veto the change. :+1:

**Comment by mjeveritt** [comment] 2019-03-15 23:13
I -think- this should have been squashed, although I don't quite remember what the root cause was at this point in time .. assigning to self to revisit and Close if Fixed.

**Comment by aliceinwire** [comment] 2019-06-10 15:29
there is still the problem ?
we can close this ?

**Comment by aliceinwire** [comment] 2021-01-15 07:09
closing as old and don't see such error anymore

**Closed by aliceinwire** 2021-01-15 07:09 UTC
Labels: D-Medium, bug
